[project]
name = "px-demo"
version = "0.8.4"
description = "pyprojectx demo project"
authors = [
    { name = "Houbie", email = "ivo@houbrechts-it.be" },
]
dependencies = [
    "numpy~=1.21",
    "matplotlib~=3.5",
]
requires-python = ">=3.7"
license = { text = "MIT" }

[project.urls]
homepage = "https://github.com/houbie/pyprojectx"

[project.optional-dependencies]
[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
test = [
    "pytest~=6.2",
]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.pylint.format]
max-line-length = 120

[tool.pyprojectx]
pdm = "pdm==1.12.6"
black = "black==21.7b0"
https = "httpie"

[tool.pyprojectx.aliases]
install = "pdm install"
build ="pdm install && pdm build"
test = "pdm run pytest"
run = "pdm run"
outdated = "pdm update --dry-run --unconstrained --top"
clean ="""\
rm -rf __pypackages__
rm -rf .pytest_cache
rm -rf dist"""
format-code = "pw@black src tests && pw@isort src tests"
check = "pw@pylint src && pw@test"
http = "@https:http"
post-json = "https POST pie.dev/post message='Pyprojectx is awesome!'"

[tool.pyprojectx.os.win.aliases]
clean = """\
rmdir /s/q __pypackages__
rmdir /s/q .pytest_cache
rmdir /s/q dist"""
