[tool.pyprojectx]
main = ["poetry", "ruff", "pre-commit", "px-utils", "httpie"]
jupyter = ["jupyterlab==4.0.10", "jupytext==1.16.0", "-e ."]

[tool.pyprojectx.aliases]
install = "poetry install"
test = "poetry run pytest"
format = ["ruff format", "ruff check --select I --fix"]
lint = ["ruff check"]
check = ["@lint", "@test"]
build = ["@install", "@check", "poetry build"]
run = "poetry run"
outdated = "poetry update --outdated"
clean = "pxrm dist .venv .ipynb_checkpoints"
post-json = "https POST pie.dev/post message='Pyprojectx is awesome!'"
notebook = "jupyter lab -y"
generate-readme = { cmd = "jupytext --to=md --opt hide_notebook_metadata=true README.ipynb", ctx = "jupyter" }

[tool.pyprojectx.os.win.aliases]
clean = "rmdir /s/q __pypackages__ .pytest_cache dist"

[project]
name = "px-demo"
version = "2.0.0"
description = "pyprojectx demo project"
authors = [
    { name = "Houbie", email = "ivo@houbrechts-it.be" },
]
requires-python = ">=3.8"
readme = { file = "README.ipynb", content-type = "application/x-ipynb+json" }
license = { text = "MIT" }

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 120
select = ["ALL"]
fixable = ["ALL"]
ignore = ["ISC001", "ANN", "FA", "FBT", "D100", "D102", "D103", "D104", "D105", "D213", "D203", "T201", "TRY003", "EM102", "COM812", "S602", "S603", "S604", "S605", "S607", "S324"]
[tool.ruff.per-file-ignores]
"tests/*" = ["S101", "I001", "INP001"]

[tool.poetry]
name = "px-demo"
version = "2.0.0"
description = "pyprojectx demo project"
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
numpy = "<1.26"
matplotlib = ">=3.5"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
