[tool.pyprojectx]
main = ["pdm", "ruff", "pre-commit", "px-utils", "httpie"]
jupyter = ["jupyterlab", "-e ."]

[tool.pyprojectx.aliases]
install = "pdm install"
test = "pdm run pytest"
format = ["ruff format", "ruff check --select I --fix"]
lint = ["ruff check"]
check = ["@lint", "@test"]
build = ["@install", "@check", "pdm build"]
run = "pdm run"
outdated = "pdm update --outdated"
clean = "pxrm dist .venv .ipynb_checkpoints"
post-json = "https POST pie.dev/post message='Pyprojectx is awesome!'"
notebook = "jupyter lab -y"

[tool.pyprojectx.os.win.aliases]
clean = "rmdir /s/q __pypackages__ .pytest_cache dist"

[tool.pdm]
package-type = "library"
[tool.pdm.dev-dependencies]
test = ["pytest>=7.4.3"]

[project]
name = "px-demo"
version = "2.0.0"
description = "pyprojectx demo project"
authors = [
    { name = "Houbie", email = "ivo@houbrechts-it.be" },
]
requires-python = ">=3.8"
readme = { file = "README.ipynb", content-type = "application/x-ipynb+json" }
license = { text = "MIT" }

dependencies = [
    "numpy<1.26",
    "matplotlib>=3.5",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.ruff]
line-length = 120
select = ["ALL"]
fixable = ["ALL"]
ignore = ["ISC001", "ANN", "FA", "FBT", "D100", "D102", "D103", "D104", "D105", "D213", "D203", "T201", "TRY003", "EM102", "COM812", "S602", "S603", "S604", "S605", "S607", "S324"]
[tool.ruff.per-file-ignores]
"tests/*" = ["S101", "I001", "INP001"]
