[tool.wraptor]
poetry = "poetry==1.1.7"
# install the current directory as local package together with ipykernel
# pw caches tool venvs based on the pip instal arguments,
# so we use './micro-pipx' in stead of '.' to create a project specific venv with ipykernel and this project installed in
ipykernel = "ipykernel ../micro-pipx"
jupyter = "jupyter"

aws = "awscli"
doitlive = "doitlive"
httpie = "httpie"

[tool.wraptor.alias]
installkernel ="ipykernel:python -m ipykernel install --name=wrapped-pi"
s3cp = "aws s3 cp --profile ivo"
livedemo = "doitlive play demo.sh"
https = "httpie:https"
http = "httpie:http"
postjson = "httpie:http POST pie.dev/post message=Awesome!"
nb = "jupyter notebook"

test = "poetry run pytest"

[tool.poetry]
name = "wrapped-pi"
version = "0.1.0"
description = "python-wraptor example"
authors = ["Houbie <ivo@houbrechts-it.be>"]

[tool.poetry.dependencies]
python = ">=3.7"
numpy = "^1.21.1"
matplotlib = "^3.4.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

