name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build ${{ matrix.os }} / ${{ matrix.python-version }} ${{ matrix.suffix }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        os: [ Ubuntu, Windows ]
        python-version: [ "3.8", "3.12" ]
        include:
          - os: Ubuntu
            image: ubuntu-latest
          - os: Windows
            image: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache .pyprojectx
        uses: actions/cache@v2
        env:
          cache-name: .pyprojectx
        with:
          path: .pyprojectx
          key: ${{ hashFiles('pyproject.toml') }}-${{ runner.os }}-${{ matrix.python-version }}-pyprojectx

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test and build
        run: |
          python pw build
